package com.mos.common.audit.enums;

public enum AuditAction {
    COIN_CREDIT,
    COIN_DEBIT,
    COIN_TRANSFER,
    ITEM_GRANT,
    ITEM_TRANSFER,
    QR_SCAN,
    TRADE_COMPLETE,
    QUEST_COMPLETE,
    SECRET_REDEEM,
    ADMIN_ACTION,
    LOCATION_DISCOVER,
    EVENT_CREATE,
    EVENT_STATUS_CHANGE,
    NUMBER_GRANT,
    QUEST_CREATE,
    QUEST_START,
    QUEST_PROGRESS,
    QUEST_CLOSE,
    TRADE_CREATE,
    TRADE_ACCEPT,
    TRADE_DECLINE,
    TRADE_CANCEL,
    SESSION_START,
    SESSION_PAUSE,
    SESSION_FINISH
}
