-- Auto-distribute social quests from pool

ALTER TABLE game_config
    ADD COLUMN quest_auto_distribute_enabled BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE game_config
    ADD COLUMN quest_auto_last_distributed_at TIMESTAMPTZ;

ALTER TABLE audit_log DROP CONSTRAINT chk_audit_log_action;
ALTER TABLE audit_log ADD CONSTRAINT chk_audit_log_action CHECK (
    action IN (
        'COIN_CREDIT', 'COIN_DEBIT', 'COIN_TRANSFER', 'ITEM_GRANT', 'ITEM_TRANSFER',
        'QR_SCAN', 'TRADE_COMPLETE', 'QUEST_COMPLETE', 'SECRET_REDEEM',
        'ADMIN_ACTION', 'LOCATION_DISCOVER',
        'EVENT_CREATE', 'EVENT_STATUS_CHANGE', 'NUMBER_GRANT',
        'QUEST_CREATE', 'QUEST_START', 'QUEST_PROGRESS', 'QUEST_CLOSE',
        'TRADE_CREATE', 'TRADE_ACCEPT', 'TRADE_DECLINE', 'TRADE_CANCEL',
        'SESSION_START', 'SESSION_PAUSE', 'SESSION_FINISH',
        'AUCTION_MODE_CHANGE', 'AUCTION_LOT_CREATE', 'AUCTION_LOT_OPEN',
        'AUCTION_LOT_SELL', 'AUCTION_LOT_CANCEL', 'AUCTION_BID',
        'LORE_REVEAL_CHANGE',
        'QUEST_BROADCAST', 'QUEST_AUTO_DISTRIBUTE_CHANGE'
    )
);
